import { Geist, Geist_Mono, Koulen, Londrina_Solid, Sometype_Mono, Newsreader, Inconsolata, Lobster} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const koulen = Koulen({
  variable: "--font-koulen",
  weight: ["400"],
  subsets: ["latin"],
});

const londrina = Londrina_Solid({
  variable: "--font-londrina",
  weight: ["400"],
  subsets: ["latin"],
});

const sometype = Sometype_Mono({
  variable: "--font-sometype",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const newsreader = Newsreader({
  variable: "--font-newsreader",
  weight: ["400"],
  subsets: ["latin"],
});

const inconsolata = Inconsolata({
  variable: "--font-inconsolata",
  weight: ["300", "400"],
  subsets: ["latin"],
});

const lobster = Lobster({
  variable: "--font-lobster", 
  weight: ["400"], 
  subsets: ['latin'], 
});

export const metadata = {
  title: "SheHacks 11",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${koulen.variable} ${londrina.variable} ${sometype.variable} ${newsreader.variable} ${inconsolata.variable} ${lobster.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
